image: node:12.10.0

cache:
  paths:
    - node_modules/
    - .cache/
pages:
  stage: build
  script:
    - npm install
    - npm run bootstrap
    - lerna run build-storybook
  artifacts:
    paths:
      - storybook-static
  only:
    - master
