image: node:12.10.0

variables:
  GITLAB_AUTH_TOKEN: $GITLAB_AUTH_TOKEN

cache:
  paths:
    - node_modules/
pages:
  stage: deploy
  script:
    - npm install
    - npm run bootstrap
    - npm run build-storybooks
  only:
    - master
