image: node:12.10.0

cache:
  paths:
    - node_modules/
    - .cache/
pages:
  stage: deploy
  script:
    - npm i
    - npm run bootstrap
    - lerna run build-storybook
  artifacts:
    paths:
      - public
  only:
    - master
