image: node:14.16

variables:
  GITLAB_AUTH_TOKEN: $GITLAB_AUTH_TOKEN

cache:
  paths:
    - node_modules/
pages:
  stage: build
  script:
    - npm install
    - npm run bootstrap
    - npm run build-storybooks
    - mv packages/core/storybook-static/ public/
  artifacts:
    paths:
      - public
  only:
    - master
